# FONT
font_family FiraCode Nerd Font
font_size 12.5

# CUSTOM THEMING
background_opacity 0.8

# ADVANCED
editor nvim
shell zsh

window_padding_width 16

detect_urls yes


# BEGIN_KITTY_THEME
# Cherry Midnight
include current-theme.conf
# END_KITTY_THEME
